config:
  nacos:
    host: ${NACOS_HOST:127.0.0.1}:18848
    username: nacos
    password: nacos
  canal:
    host: 127.0.0.1
    port: 11111
    destination: example
    username: canal
    password: canal

spring:
  cloud:
    nacos:
      username: ${config.nacos.username}
      password: ${config.nacos.password}
      discovery:
        server-addr: ${config.nacos.host}
        namespace: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/plaza?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: root
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST:127.0.0.1}
      database: 2
      lettuce:
        pool:
          min-idle: 1
          max-idle: 5
          max-active: 10
  elasticsearch:
    host: ${ES_HOST:81.71.45.30}
    port: ${ES_PORT:9200}
    username: ${ES_USERNAME:elastic}
    password: ${ES_PASSWORD:elastic}